### ISSUE TITLE
v3n0m through tor - ignoring false on login

### ISSUE THREAD

**Issue by Impulse-PW** [d4rkcat/v3n0m#2]
I don't know if this is a bug, or me making a mistake. But I have TOR running (socks5 : 127.0.0.1 : 9050)

Which works fine connecting through IRC and Firefox. However, when I try to use TOR with v3n0m it goes like so:

I choose option 5: 
Requires Username/Password? Type True or False?  : False

I tell it socks5, then I give it the address 127.0.0.1, and finally the port 9050.
Regardless, it asks for the "Proxy Account Username" and "Password". (if I leave blank, the main screen loads again and says "Proxy Enabled: [ False ]"

Any ideas?

**Comment by d4rkcat** [comment]
Hi mate, 
   v3nom is not actually my script, it's a fork of https://github.com/v3n0m-Scanner/V3n0M-Scanner
Best to download their version and try again, if it doesn't work post an issue on that page.
Cheers
